[2025-07-04T04:46:03.843+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-04T04:46:04.054+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: products_prices_dag.mail_content scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T04:46:04.066+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: products_prices_dag.mail_content scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T04:46:04.068+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-04T04:46:04.131+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): mail_content> on 2025-07-03 00:00:00+00:00
[2025-07-04T04:46:04.142+0000] {standard_task_runner.py:63} INFO - Started process 3234 to run task
[2025-07-04T04:46:04.150+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'products_prices_dag', 'mail_content', 'scheduled__2025-07-03T00:00:00+00:00', '--job-id', '203', '--raw', '--subdir', 'DAGS_FOLDER/products_prices_dag.py', '--cfg-path', '/tmp/tmp43p1thbw']
[2025-07-04T04:46:04.156+0000] {standard_task_runner.py:91} INFO - Job 203: Subtask mail_content
[2025-07-04T04:46:04.192+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-04T04:46:04.265+0000] {task_command.py:426} INFO - Running <TaskInstance: products_prices_dag.mail_content scheduled__2025-07-03T00:00:00+00:00 [running]> on host e43ce2a1e7a4
[2025-07-04T04:46:04.376+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='karthik' AIRFLOW_CTX_DAG_ID='products_prices_dag' AIRFLOW_CTX_TASK_ID='mail_content' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-03T00:00:00+00:00'
[2025-07-04T04:46:04.378+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-04T04:46:04.392+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-04T04:46:04.393+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/products_prices_dag.py", line 18, in formate_mail
    result_value = ti.xcom_pull(task_id='price_compare')
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'
[2025-07-04T04:46:04.413+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=products_prices_dag, task_id=mail_content, run_id=scheduled__2025-07-03T00:00:00+00:00, execution_date=20250703T000000, start_date=20250704T044604, end_date=20250704T044604
[2025-07-04T04:46:04.426+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 203 for task mail_content (TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'; 3234)
[2025-07-04T04:46:04.444+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-04T04:46:04.470+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-04T04:46:04.474+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
