[2025-06-30T03:40:42.475+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-30T03:40:42.512+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_dag.insert_data scheduled__2025-06-29T00:00:00+00:00 [queued]>
[2025-06-30T03:40:42.523+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_dag.insert_data scheduled__2025-06-29T00:00:00+00:00 [queued]>
[2025-06-30T03:40:42.524+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-30T03:40:42.601+0000] {taskinstance.py:2330} INFO - Executing <Task(MySqlOperator): insert_data> on 2025-06-29 00:00:00+00:00
[2025-06-30T03:40:42.611+0000] {standard_task_runner.py:63} INFO - Started process 226 to run task
[2025-06-30T03:40:42.620+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_dag', 'insert_data', 'scheduled__2025-06-29T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/mysql.py', '--cfg-path', '/tmp/tmpzknimgf4']
[2025-06-30T03:40:42.627+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask insert_data
[2025-06-30T03:40:42.672+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-30T03:40:42.832+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_dag.insert_data scheduled__2025-06-29T00:00:00+00:00 [running]> on host 8a42fea10265
[2025-06-30T03:40:43.033+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Karthik' AIRFLOW_CTX_DAG_ID='mysql_dag' AIRFLOW_CTX_TASK_ID='insert_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-29T00:00:00+00:00'
[2025-06-30T03:40:43.035+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-30T03:40:43.063+0000] {sql.py:276} INFO - Executing: 
        INSERT INTO test_table (name) VALUES ('John Doe')
        
[2025-06-30T03:40:43.084+0000] {base.py:84} INFO - Using connection ID 'mysql_conn' for task execution.
[2025-06-30T03:40:43.101+0000] {base.py:84} INFO - Using connection ID 'mysql_conn' for task execution.
[2025-06-30T03:40:43.187+0000] {sql.py:487} INFO - Running statement: 
        INSERT INTO test_table (name) VALUES ('John Doe')
        , parameters: None
[2025-06-30T03:40:43.205+0000] {sql.py:496} INFO - Rows affected: 1
[2025-06-30T03:40:43.221+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-30T03:40:43.242+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mysql_dag, task_id=insert_data, run_id=scheduled__2025-06-29T00:00:00+00:00, execution_date=20250629T000000, start_date=20250630T034042, end_date=20250630T034043
[2025-06-30T03:40:43.319+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-30T03:40:43.341+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
