[2025-07-04T05:40:55.520+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-04T05:40:55.590+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: products_prices_dag.mail_group.generate_email scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T05:40:55.615+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: products_prices_dag.mail_group.generate_email scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T05:40:55.617+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-07-04T05:40:55.647+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): mail_group.generate_email> on 2025-07-03 00:00:00+00:00
[2025-07-04T05:40:55.663+0000] {standard_task_runner.py:63} INFO - Started process 4995 to run task
[2025-07-04T05:40:55.673+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'products_prices_dag', 'mail_group.generate_email', 'scheduled__2025-07-03T00:00:00+00:00', '--job-id', '221', '--raw', '--subdir', 'DAGS_FOLDER/products_prices_dag.py', '--cfg-path', '/tmp/tmp8w0iuij2']
[2025-07-04T05:40:55.684+0000] {standard_task_runner.py:91} INFO - Job 221: Subtask mail_group.generate_email
[2025-07-04T05:40:55.720+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-04T05:40:55.800+0000] {task_command.py:426} INFO - Running <TaskInstance: products_prices_dag.mail_group.generate_email scheduled__2025-07-03T00:00:00+00:00 [running]> on host e43ce2a1e7a4
[2025-07-04T05:40:56.031+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='karthik' AIRFLOW_CTX_DAG_ID='products_prices_dag' AIRFLOW_CTX_TASK_ID='mail_group.generate_email' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-03T00:00:00+00:00'
[2025-07-04T05:40:56.035+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-04T05:40:56.200+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-04T05:40:56.202+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/products_prices_dag.py", line 28, in format_email_and_save_csv
    df.to_csv(csv_path, index=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: '/opt/airflow/dags/scripts/fakestoreapi/price_drop.csv'
[2025-07-04T05:40:56.246+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=products_prices_dag, task_id=mail_group.generate_email, run_id=scheduled__2025-07-03T00:00:00+00:00, execution_date=20250703T000000, start_date=20250704T054055, end_date=20250704T054056
[2025-07-04T05:40:56.278+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 221 for task mail_group.generate_email ([Errno 13] Permission denied: '/opt/airflow/dags/scripts/fakestoreapi/price_drop.csv'; 4995)
[2025-07-04T05:40:56.332+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-04T05:40:56.381+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-04T05:40:56.434+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
