[2025-06-30T06:13:10.479+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-30T06:13:10.666+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_dag.check_price_diff manual__2025-06-30T06:13:05.566111+00:00 [queued]>
[2025-06-30T06:13:10.683+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_dag.check_price_diff manual__2025-06-30T06:13:05.566111+00:00 [queued]>
[2025-06-30T06:13:10.684+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-30T06:13:10.707+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_price_diff> on 2025-06-30 06:13:05.566111+00:00
[2025-06-30T06:13:10.717+0000] {standard_task_runner.py:63} INFO - Started process 1274 to run task
[2025-06-30T06:13:10.724+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_dag', 'check_price_diff', 'manual__2025-06-30T06:13:05.566111+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/mysql.py', '--cfg-path', '/tmp/tmpynpjarbg']
[2025-06-30T06:13:10.730+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask check_price_diff
[2025-06-30T06:13:10.761+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-30T06:13:10.904+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_dag.check_price_diff manual__2025-06-30T06:13:05.566111+00:00 [running]> on host 76cdd04f4df6
[2025-06-30T06:13:11.097+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Karthik' AIRFLOW_CTX_DAG_ID='mysql_dag' AIRFLOW_CTX_TASK_ID='check_price_diff' AIRFLOW_CTX_EXECUTION_DATE='2025-06-30T06:13:05.566111+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-30T06:13:05.566111+00:00'
[2025-06-30T06:13:11.100+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-30T06:13:11.121+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-30T06:13:11.123+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 233, in execute
    self.op_kwargs = self.determine_kwargs(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 244, in determine_kwargs
    return KeywordParameters.determine(self.python_callable, self.op_args, context).unpacking()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 163, in determine
    raise ValueError(f"The key {name!r} in args is a part of kwargs and therefore reserved.")
ValueError: The key 'conn' in args is a part of kwargs and therefore reserved.
[2025-06-30T06:13:11.139+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=mysql_dag, task_id=check_price_diff, run_id=manual__2025-06-30T06:13:05.566111+00:00, execution_date=20250630T061305, start_date=20250630T061310, end_date=20250630T061311
[2025-06-30T06:13:11.160+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 78 for task check_price_diff (The key 'conn' in args is a part of kwargs and therefore reserved.; 1274)
[2025-06-30T06:13:11.180+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-30T06:13:11.209+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-30T06:13:11.214+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
